version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8099
    volumes:
      - .:/app
    ports:
      - "8099:8099"
    depends_on:
      - db